import dotenv from 'dotenv';

dotenv.config();

const {
  PORT,
  DB_ENV,
  POSTGRES_HOST,
  POSTGRES_PORT,
  POSTGRES_DB,
  POSTGRES_DB_TEST,
  POSTGRES_USER,
  POSTGRES_PASSWORD,
  BCRYPT_PASSWORD,
  SALT_ROUNDS,
  TOKEN_SECRET,
} = process.env;

export default {
  PORT: PORT,
  HOST: POSTGRES_HOST,
  DBPORT: POSTGRES_PORT,
  DATABASE: DB_ENV === 'dev' ? POSTGRES_DB : POSTGRES_DB_TEST,
  USER: POSTGRES_USER,
  PASSWORD: POSTGRES_PASSWORD,
  BCRYPT: BCRYPT_PASSWORD,
  SALT: SALT_ROUNDS,
  TOKEN_SECRET: TOKEN_SECRET,
};
